inherits = "github_light"

keyword = { modifiers = ["bold"] }
"ui.background" = { bg = "white" }
"ui.statusline" = { bg = "apricot" }

[palette]
white = "#ffffff"
lavender = "#a4a0e8"
apricot = "#f47868"
